url: https://apoorvasingla.github.io

# Site settings
title: Architecture Portfolio
phone: +91-7597718148
email: apoorvasingla01@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: apoorva, singla, mnit, jaipur, architect

# Build settings
markdown: kramdown
permalink: "/index"

collections:
    projects:
        output: true
        permalink: project/:title

skills:
  - name: Autodesk Autocad
    percent: 85
  - name: Autodesk Revit
    percent: 50
  - name: Adobe Photoshop
    percent: 85
  - name: Google Sketchup
    percent: 80
  - name: Lumion
    percent: 50
  - name: V-ray
    percent: 70
  - name: Manual Sketching
    percent: 75
  - name: Microsoft Office
    percent: 90
