url: https://apoorvasingla.github.io

# Site settings
title: Architecture Portfolio
phone: +91-XXXXXXXXXX
email: XXXXX@gmail.com
description: This is an Architectural Portfolio of Ar. Apoorva Singla
keywords: apoorva, singla, mnit, jaipur, architect

# Build settings
markdown: kramdown
permalink: "/index"

collections:
    projects:
        output: true
        permalink: project/:title

skills:
  - name: Autodesk Autocad
    percent: 85
  - name: Autodesk Revit
    percent: 50
  - name: Adobe Photoshop
    percent: 85
  - name: Google Sketchup
    percent: 80
  - name: Lumion
    percent: 50
  - name: V-ray
    percent: 70
  - name: Manual Sketching
    percent: 75
  - name: Microsoft Office
    percent: 90
